config/routes.rb
ForestChalet::Application.routes.draw do

  get "logout" => "sessions#destroy", :as => "logout"

  resources :sessions

  match "posts/category(/:name)" => "posts#category"
  match "posts/tag(/:name)" => "posts#tag"

  resources :posts, :only => [:index, :show]

  get "projects" => "posts#projects", :as => :projects

  root :to => "posts#index"

  namespace :chalet do
    root :to => "base#index"
    resources :posts, :except => :show
  end

end

app/models/post.rb
require 'redcarpet/compat'

class Post < ActiveRecord::Base

  default_scope order 'created_at DESC'

  paginates_per 5

  acts_as_taggable_on :categories
  acts_as_taggable_on :tags

  belongs_to :user

  attr_accessible :cached_tag_list, :category, :comments_count, :content, :content_html, :slug_url, :summary, :title, :view_count

  serialize :cached_tag_list, Array

  before_save :markdown2html

  def markdown2html
    self.content_html = Markdown.new(self.content).to_html
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  attr_accessible :username, :email, :password, :password_confirmation

  validates_confirmation_of :password
  validates_presence_of :password, :username, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chalet/base_controller.rb
# encoding: utf-8
class Chalet::BaseController < ApplicationController

  before_filter :require_login

  layout "chalet"

  def index

  end

end

app/controllers/chalet/posts_controller.rb
# encoding: utf-8
class Chalet::PostsController < Chalet::BaseController

  # GET /posts
  # GET /posts.json
  def index
    # @posts = Post.page params[:page]
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to chalet_posts_url(chrome_bug_workaround: 177855), notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to edit_chalet_post_path(@post), notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to chalet_posts_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.page params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def projects
    @posts = Post.tagged_with("Project", :on => :categories )
  end

  def category
    if params[:name].nil?
      @posts = Post.page params[:page]
    else
      @posts = Post.tagged_with( params[:name], :on => :categories ).page params[:page]
    end
    render :index
  end

  def tag
    if params[:name].nil?
      @posts = Post.page params[:page]
    else
      @posts = Post.tagged_with( params[:name], :on => :tags ).page params[:page]
    end
    render :index
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html# show.html.erb
      format.json { render json: @post }
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to chalet_root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Email or password was invalid"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/helpers/application_helper.rb
# encoding: utf-8
module ApplicationHelper

  # gravatar image src
  # <%= gravatar "miclle.zheng@gmail.com", 150 %>
  # => "http://gravatar.com/avatar/004794ff3508e44c4902fd82ef4027f4.png?default=monsterid&size=150"
  # default_image:  ['http://example.com/images/default_gravitar.jpg', "identicon", "monsterid", "wavatar", "404" ]
  # filetype:       ['gif', 'jpg' or 'png'].  Gravatar's default is png
  # rating:         ['G', 'PG', 'R', 'X']. Gravatar's default is G
  # size:           (1..512), default is 80
  def gravatar(email, options = {})
    configuration = {
      :default_image  =>  nil,
      :file_type      =>  "png",
      :size           =>  80
    }
    configuration.update(options) if options.is_a?(Hash)

    "http://gravatar.com/avatar/#{Digest::MD5.hexdigest(email.downcase)}.#{configuration[:file_type]}?default=#{configuration[:default_image]}&size=#{configuration[:size]}" unless email.blank?
  end

  # Format time
  def strftime(time, format = "%m/%d %H:%M")
    time.strftime(format) unless time.blank?
  end

  # Date format
  # date_format dateime => "2003-04-09"
  def date_format(datetime)
    datetime.strftime("%Y年%m月%d日") unless datetime.blank?
  end

  # Datetime format
  # datetime_format(dateime) result: "2003年04月09日 15:30:50"
  def datetime_format(datetime, options={})
    configuration = { :year => true, :month => true, :day => true, :hour => true, :minute => true, :second => false }
    configuration.update(options) if options.is_a?(Hash)
    format = ""
    format << "%Y-" if configuration[:year]
    format << "%m-" if configuration[:month]
    format << "%d " if configuration[:day]
    format << "%H"  if configuration[:hour]
    format << ":%M" if configuration[:minute]
    format << ":%S" if configuration[:second]
    datetime.strftime(format) unless datetime.blank?
  end

end

app/helpers/chalet/base_helper.rb
module Chalet::BaseHelper
end

app/helpers/chalet/posts_helper.rb
module Chalet::PostsHelper
end

app/views/chalet/posts/_form.html.erb
<%= form_for([:chalet, @post]) do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="page-header">
    <div class="form-inline">
    <%= f.text_field :title, :class => "input-xxlarge", :placeholder => "Post title", :require => true %>

    <a href="#post-meta" role="button" class="btn" data-toggle="modal">Meta <i class="icon-arrow-down"></i></a>

    <%= f.submit "Save", class: "btn btn-info" %>

    <%= link_to "Delete", chalet_post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger pull-right" if action_name == "edit" %>
    </div>
  </div>

  <!-- Modal -->
  <div id="post-meta" class="" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

    <div class="modal-body form-horizontal">
      <div class="control-group">
        <%= f.label :tag_list, "Tags", :class => "control-label" %>
        <div class="controls">
          <%= f.text_field :tag_list, :placeholder => "Tag..." %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :category_list, "Category", :class => "control-label" %>
        <div class="controls">
          <%= f.text_field :category_list, :placeholder => "Category" %>
        </div>
      </div>

    </div>
  </div>

  <div class="content-section" id="markdown-editor">
    <div id="markdown-preview" class="markdown-preview">
      Preview content
    </div>

    <div id="markdown-input">
      <%= f.text_area :content, class: "markdown-input", data: { "markdown-preview" => "#markdown-preview"} %>
    </div>
  </div>

<% end %>

app/views/chalet/posts/edit.html.erb
<%= render 'form' %>

app/views/chalet/posts/index.html.erb
<div class="page-header">
  <h3 class="pull-left">Posts</h3>
  <%= link_to "New Post", new_chalet_post_path, class: "btn btn-info pull-right" %>
</div>

<div class="content-section">

  <% @posts.each do |post| %>
    <article class="post-item">
      <h4>
        <%= link_to post.title, edit_chalet_post_path(post) %>
        <small class="date"><%= post.created_at.strftime("%Y.%m.%d") %></small>
      </h4>

      <div class="text"><%= truncate post.content, :length => 150, :separator => '...' %></div>

      <div class="meta">

        <div class="comment">
          Comments: <%=  post.comments_count %>
        </div>

        <div class="category">Category: <%= post.category_list %></div>

        <div class="tags">Tags: <%= post.tag_list %></div>

      </div>
    </article>
  <% end  %>

</div>

app/views/chalet/posts/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ForestChalet</title>
    <%= csrf_meta_tags %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <%= yield :head %>

  </head>
  <body>

    <aside>
      <div id="avatar-area"><a href="/"><%= image_tag gravatar("miclle.zheng@gmail.com", :size => 50), :alt => "Miclle Zheng" -%></a></div>

      <!-- <div id="vc-container" class="vc-container">
        <div class="vc-tape-wrapper">
          <div class="vc-tape">
            <div class="vc-tape-back">
              <div class="vc-tape-wheel vc-tape-wheel-left"><div></div></div>
              <div class="vc-tape-wheel vc-tape-wheel-right"><div></div></div>
            </div>
            <div class="vc-tape-front vc-tape-side-a"><span>A</span></div>
            <div class="vc-tape-front vc-tape-side-b"><span>B</span></div>
          </div>
        </div>
        <div class="vc-loader"></div>
      </div> -->
      <!-- //vc-container -->

      <section id="login">
        <%= form_tag sessions_path, :class => "clearfix" do %>

          <%= alert %>

          <ul class="clearfix">
            <li>
              <%= label_tag :email %>
              <%= text_field_tag :email, params[:email], :placeholder => "yourname@email.com", :required => true, :tabindex => 1 %>
            </li>

            <li>
              <%= label_tag :password %>
              <%= password_field_tag :password, nil, :placeholder => "password", :required => true, :tabindex => 2 %>
            </li>

            <li>
              <%= submit_tag "Log in", :class => "btn", :tabindex => 3 %>
            </li>
          </ul>

        <% end %>
      </section>

      <section id="aside-footer">
        <div class="brand">
          <!-- <a href="http://markdown.miclle.com/" target="_blank"><i class="icon-music"></i></a> -->
          <%= link_to content_tag('i', nil, class: "icon-beaker"), projects_path %>
          <a href="http://github.com/miclle" target="_blank"><i class="icon-github-sign"></i></a>
          <a href="http://twitter.com/miclle" target="_blank"><i class="icon-twitter-sign"></i></a>
        </div>

        <div class="copyright">
          <span>&copy; Miclle.Zheng . Powered by</span> <a href="https://github.com/miclle/forest-chalet" target="_blank" title="Forest Chalet">Forest&nbsp;Chalet</a>
        </div>
      </section>

      <%= link_to content_tag('i', nil, class: "icon-cog"), "javascript:;", :id => "setting-icon" %>
    </aside>

    <section id="main" data-pjax-container>
      <%= yield %>
    </section>

    <a id="fork-me-on-github" href="https://github.com/miclle" target="_blank"><img src="http://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png" alt="Fork me on GitHub"></a>

    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-8236884-5']);
      _gaq.push(['_trackPageview']);
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>

    <script src="http://coolshell.cn/wp-content/themes/inove/js/jquery.bpopup-0.8.0.min.js"></script>

    <script type="text/javascript">
    ;(function($) {
      $(function() {
        var url=document.referrer;
        if ( url && url.search("http://")>-1) {
          var refurl =  url.match(/:\/\/(.[^/]+)/)[1];
          if(refurl.indexOf("baidu.com")>-1){
            $('#nobaidu_dlg').bPopup();
          }
        }
      });

    })(jQuery);
    </script>

    <div id="nobaidu_dlg" style="background-color:#fff; border-radius:15px;color:#000;display:none;padding:20px;min-width:450px;min-height:180px;">
      <img src="http://coolshell.cn/wp-content/themes/inove/img/nobaidu.jpg" align="left">
      <p style="margin-left:200px;margin-top: 20px; line-height: 30px;">
         检测到你还在使用百度这个搜索引擎，<br/>
         做为一个程序员，这是一种自暴自弃！<br/>
         <br/>
      </p>
      <p align="center" style="margin-top:20px;">
        百度推广更垃圾，一天打我四个电话，号码:021-39006017/39005390 SB
      </p>
    </div>

  </body>
</html>

app/views/layouts/chalet.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <title>Admin - Forest-Chalet</title>
    <%= stylesheet_link_tag    "chalet/chalet", :media => "all" %>
    <%= javascript_include_tag "chalet/chalet" %>
  </head>
  <body>

    <section>

      <div id="sidebar">
        <div id="avatar-area">
          <%= link_to image_tag(gravatar(current_user.email, :size => 160)), "http://gravatar.com/", :title => "Change your avatar at Gravatar.com." %>
        </div>

        <ul class="nav nav-list">

          <li class="nav-header">List header</li>

          <li class="<%= 'active' if controller_name == "base" -%>">
            <%= link_to content_tag('i', nil, class: "icon-white icon-home") + " Index", chalet_root_path %>
          </li>

          <li class="<%= 'active' if controller_name == "posts" -%>">
            <%= link_to content_tag('i', nil, class: "icon-white icon-folder-open") + " Post", chalet_posts_path %>
          </li>

          <li class="divider"></li>

          <li>
            <%= link_to content_tag('i', nil, class: "icon-white icon-user") + " Account", "#" %>
          </li>

          <li>
            <%= link_to content_tag('i', nil, class: "icon-white icon-off") + " Logout", logout_path %>
          </li>

        </ul>

      </div>

      <div id="main">
        <%= yield %>
      </div>

    </section>

  </body>
</html>

app/views/posts/index.html.erb
<div id="container">

  <nav class="breadcrumb">
    <h3 class="article-title">
      <%= link_to "All Articles", posts_path %>
      <%= content_tag('i', nil, class: "icon-arrow-right") + content_tag('span', params[:name]) unless params[:name].blank? %>
      <a href="#" class="action">Category<i class="icon-arrow-right"></i></a>
    </h3>
  </nav>

  <% @posts.each do |post| %>
    <article class="<%= cycle("even", "odd") -%>">

      <h2 class="title">
        <%= link_to post.title, post %>
        <span class="date"><%= post.created_at.strftime("%Y.%m.%d") %></span>
      </h2>

      <div class="meta">
        <%= link_to "Comments", {:controller => "posts", :action => 'show', :id => post.id, :anchor => 'disqus_thread'}, 'data-disqus-identifier' => "miclle-post-#{post.id}" %>
      </div>

      <div class="text">
        <%= raw post.content_html %>
      </div>

      <div class="meta">
        <% unless post.category_list.blank? %>
        <span class="category">
          Category:
          <% post.category_list.each do |category| %>
            <%= link_to category, {:controller => :posts, :action => :category, :name => category } %>
          <% end %>
        </span>
        <% end %>

        <% unless post.tag_list.blank? %>
        <span class="tags">
          Tags:
          <% post.tag_list.each do |tag| %>
            <%= link_to tag, {:controller => :posts, :action => :tag, :name => tag } %>
          <% end %>
        </span>
        <% end %>
      </div>

    </article>
  <% end  %>

  <div class="pagging-holder">
    <%= paginate @posts %>
  </div>

  <div class="model">
    <h2>TAGS</h2>
    <div class="content tags">
      <% tag_cloud(Post.tag_counts, %w(css1 css2 css3 css4)) do |tag, css_class| %>
        <%= link_to tag.name, {:controller => :posts, :action => :tag, :name => tag.name }, :class => css_class %>
      <% end %>
    </div>
  </div>

  <div class="model">
    <h2>CATEGORIES</h2>
    <div class="content tags">
      <% Post.category_counts.each do |category| %>
        <li>
          <%= link_to category.name, {:controller => :posts, :action => :category, :name => category.name }, :class=>"active" %>
        </li>
      <% end %>
    </ul>
  </div>

</div>

<script type="text/javascript">
/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
var disqus_shortname = 'miclle'; // required: replace example with your forum shortname

/* * * DON'T EDIT BELOW THIS LINE * * */
(function () {
    var s = document.createElement('script'); s.async = true;
    s.type = 'text/javascript';
    s.src = '//' + disqus_shortname + '.disqus.com/count.js';
    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

app/views/posts/projects.html.erb
<div id="container">

  <nav class="breadcrumb">
    <h3 class="article-title">
      <%= link_to "All Projects", projects_path %>
    </h3>
  </nav>

  <% @posts.each do |post| %>
    <article class="<%= cycle("even", "odd") -%>">

      <h2 class="title">
        <%= link_to post.title, post %>
        <span class="date"><%= post.created_at.strftime("%Y.%m.%d") %></span>
      </h2>

      <div class="meta">
        <% unless post.category_list.blank? %>
        <span class="category">
          Category:
          <% post.category_list.each do |category| %>
            <%= link_to category, {:controller => :posts, :action => :category, :name => category } %>
          <% end %>
        </span>
        <% end %>

        <% unless post.tag_list.blank? %>
        <span class="tags">
          Tags:
          <% post.tag_list.each do |tag| %>
            <%= link_to tag, {:controller => :posts, :action => :tag, :name => tag } %>
          <% end %>
        </span>
        <% end %>
      </div>

      <div class="text">
        <%= raw post.content_html %>
      </div>

    </article>
  <% end %>

</div>

app/views/posts/show.html.erb
<div id="container">

  <article>

    <h2 class="title">
      <%= @post.title %>
      <span class="date"><%= @post.created_at.strftime("%Y.%m.%d") %></span>
    </h2>

    <div class="entry">
      <%= raw @post.content_html %>
    </div>

    <div class="meta">
      <p>
        Posted in:
        <% @post.category_list.each do |category| %>
          <%= link_to category, {:controller => :posts, :action => :category, :name => category }%>
        <% end %>
      </p>

      <p>Tags:
        <% @post.tag_list.each do |tag| %>
          <%= link_to tag, {:controller => :posts, :action => :tag, :name => tag } %>
        <% end %>
      </p>
    </div>

    <div id="disqus_thread"></div>

    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'miclle'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

  </article>
</div>